davidyaha/graphql-redis-subscriptions

- src/redis-pubsub.ts
- src/test/tests.ts
This is done when unsubscribing
Should fix #7
> Release retained memory by the subscriptionMap

- package.json
- src/pubsub-async-iterator.ts
- src/redis-pubsub.ts
- src/test/integration-tests.ts
- src/test/tests.ts
- src/with-filter.ts
- tsconfig.json
I think the best solution would be to submit a PR directly to graphql-subscriptions, changing the PubSubEngine from an interface to an abstract class, so that all classes which inherit the PubSubEngine super abstract class will already have an AsyncIterator implemented.
> Implemented Generic AsyncIterator

- README.md
- package.json
- src/redis-pubsub.ts
- src/test/integration-tests.ts
- src/test/tests.ts
Luckily, ioredis implements an almost identical API:
https://github.com/luin/ioredis/wiki/Migrating-from-node_redis
Note:
I deleted the ^ from typescript in package.json because it installs version 2.4 and this project isn't compatible with it - so the CI won't pass.
> Replace 'redis' library with 'ioredis' for Cluster and Sentinel support

- src/redis-pubsub.ts
subsRefsMap can grow unbounded since the keys are never cleaned up. (this affects the rabbitmq version, looks like).
also fixes edge case of invalid index.
might be worthwhile to move to a hashtable like https://github.com/chad3814/node-hashtable or even redis to store the refs.
alternatively, if you wanna stay in JS land, i might suggest `subsRefMap = {[channel]: Set<onMessageHandler>}` and if CPU is more important than memory, building an index like `{[socketId]: Set<onMessageHandler>}` to replace subscriptionMap for fast unsubscribes as you currently have. I wouldn't do this though. My guess is that by the time the subsRefMap gets large enough to warrant a subscriptionsMap index, you won't have the memory for it, so it'd be better to keep to a single object & just iterate over it. …
> fix subsRefsMap mem leak

- src/redis-pubsub.ts
Currently `connect` and `error` event listeners are automatically applied regardless of whether or not redis streams are explicitly supplied.
If the library user is explicitly providing their own redis streams I think it makes sense to let them handle the application of event listeners (minus of course the `message` event listener) themselves.
> Only apply event listeners automatically if no pub/sub instances were provided

- .travis.yml
According to [nodejs/release](https://github.com/nodejs/release), Node 6 will be transitioned to Maintenance LTS on April 30, 2018 and will reach End of Life on April 2019.
Travis build should target Node stable (9.X) and Active LTS (8.X)
https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Specifying-Node.js-versions
> Travis build should target node stable and lts

- package.json
For: `--type-check is deprecated. You only need --project to enable rules which need type information.`
Tests should not be run on `npm install`, as the tests have a dependency on a local redis instance existsing. Move the tests to `prepublishOnly`
https://docs.npmjs.com/misc/scripts
> removed --typecheck, set prepublishOnly

- package.json
The older version of Iterall has memory leak issues. 
With large amounts of messages published, you'll run out of memory.
This describes the issue.
https://github.com/apollographql/graphql-subscriptions/issues/97
> Update Iterall to latest version 1.1.3 => 1.2.2

- README.md
Changes `retry_strategy` to `retryStrategy` since this is the option expected by ioredis.
Changed the default value to be just like their [current documentation on Auto-reconnect](https://github.com/luin/ioredis/blob/98ebeec1acd2067e52169f53e57e989ebbf671ff/README.md#auto-reconnect).
> Fix issue #164

- src/redis-pubsub.ts
Imagine you have this subscription resolver with a payload type:
```ts
Subscription: {
[CREATE_USER_TOPIC]: {
resolve: (payload: CreateUserPayload) => new User(payload.user),
subscribe: () => pubsub.asyncIterator(CREATE_USER_TOPIC),
},
},
```
And now you can share the type and protect the publish too:
```ts
pubsub.publish<CreateUserPayload>(CREATE_USER_TOPIC, createUserPayload),
```
> Make publish generic to allow sharing types

- src/redis-pubsub.ts
- src/test/tests.ts
Fixes #182.
Allows to pass a custom deserialize function, for instance to retrieve class instances.
> Allow to pass a custom serializer and deserializer

- src/redis-pubsub.ts
- src/test/tests.ts
ioredis' quit() is async.. this change allow caller to wait so proper shutdown can be achieved via waiting for close() method
> Make it possible to wait until all redis instances finish the quit routine

- README.md
Add claritifcation about incorrect deserialization of custom objects without a custom reviver.
> Clarify the necessity of a reviver

- src/redis-pubsub.ts
`ioredis` recently published a new version with built-in types.
Those types are not 100% compatible with the types declared in `@types/ioredis`, but with this PR and luin/ioredis#1552 everything should work again.
> feat: prepare for ioredis v5

- src/redis-pubsub.ts
`new IORedis('redis://localhost:6379/')` is a valid way to construct an IORedis client.
Updated `PubSubRedisOptions.connection` to allow for strings as well.
Tested in a project dependent upon this library.
See https://github.com/luin/ioredis#connect-to-redis
> fix: construct IORedis with strings

- package-lock.json
- package.json
Ioredis was updated to version 5.2.4 which breaks type compatibility with this package.
This PR updates ioredis to the newest version + it removes the dependency to the definitely typed package as ioredis provides its own types now, see:
https://www.npmjs.com/package/@types/ioredis
> update ioredis and remove deprecated types

- package.json
- src/redis-pubsub.ts
- src/test/integration-tests.ts
- When setting the to messageEventName: 'messageBuffer', the channel is received as buffer. I have added a check to set it as such.
- The buffer is also serialized as json when so I have checked if it as a buffer and return it as it is.
תודה !
> Fix: buffer messages from external resource

- .github/workflows/test.yml
The grokzen/redis-cluster:latest image is not latest: https://github.com/Grokzen/docker-redis-cluster/issues/162.
This PR pins the version to 7.0.10, which is currently the latest.
> Fix CI by using pinned version of redis-cluster

- src/index.ts
Exports the type definitions for configuration so we don't need to import like this:
`import type { PubSubRedisOptions } from 'graphql-redis-subscriptions/dist/redis-pubsub';`
> chore: export type definitions for options

- src/redis-pubsub.ts
- src/test/tests.ts
Fix for #598
I created a unit test that reproduces the scenario described in the issue. This is unfortunately a convoluted test. Only the subscribe/unsubscribe flow is exercised. No message delivery is attempted. 
As for the fix, we keep a pending state per channel, `subsPendingRefsMap`, before a new remote subscribe call is made to redis. That state is removed once the redis call is completed. The state keeps track of the subscription initiated while the redis call is in flight. The state also keeps a reference to the initial subscription promise. 
I had to use a deferred promise in the state. :crying_cat_face: The state must be initialized before executing the promise but the execution is done in the promise constructor.
> Fix concurrent subscribe race condition

- tsconfig.json
In order to make debugging easier, build the library into es2020 instead of es5.
Transpiling async..await into es5 makes using debugger harder than it needs to be.
> build: target es2020 instead of es5

- .github/dependabot.yml
- .github/workflows/test.yml
I noticed that github actions was complaining about old versions of these actions.
> Update github actions and let dependabot maintain them
